Feature/allowed characters
synaptic-cl/simple-shiro-permissions pull request #7
Opened 2021-05-27 18:49 UTC by djuretic

Se agregaron los caracteres `.`, `-` y `_` como permitidos en los nombres de los domain y actions.

2021-05-27 18:56 UTC, FelipeRubilar commented on index.js
> +    // [ACTION]:*
```suggestion
    // *:[ACTION]
```

2021-05-27 18:57 UTC, FelipeRubilar commented on index.js
> +      return permission.startsWith(`${domain}:`) && permission.endsWith(`:${action}`)
```suggestion
      return permission.endsWith(`:${action}`)
```

2021-05-27 19:10 UTC, FelipeRubilar requested changes
Podríamos implementar también la opción de permitir o no los `*`, no se si en este mismo PR pero eventualmente xd

2021-05-27 19:10 UTC, FelipeRubilar commented on test.js
> +  it('It should validate `*:view,read`', () => {
```suggestion
  it('It should validate `*:view,create`', () => {
```

2021-05-27 21:26 UTC, djuretic commented on test.js
> +  it('It should validate `*:view,read`', () => {
Ahora sí debería estar corregido

2021-05-27 21:28 UTC, FelipeRubilar commented on test.js
> -    return done()
Me faltaron estos 😬 La descripción dice 'read' pero el test usa 'create'

2021-05-28 02:04 UTC, FelipeRubilar approved these changes

2021-06-01 20:56 UTC, merged